---
header_title: CPANSec
author: CPAN Security Outreach & Information Project
description: >-
  CPAN Security Group (CPANSec) ðŸ¦†
baseurl: ""
url: "https://security.metacpan.org"
domain: security.metacpan.org
show_excerpts: true
list_title: CPANSec News

header_pages:
  - docs/report.md
  - docs/README.md
  - presentations/README.md

repository: CPAN-Security/security.metacpan.org
github_username: CPAN-Security
## Friendica links not supported yet in minima template, so
## we use a mastodon icon in the meanwhile
#friendica:
#  - { username: cpan_security, instance: perl.social }
mastodon:
  - { username: cpansec, instance: fosstodon.org }

paginate: 5
paginate_path: "/news/page:num/"

# Build settings
theme: minima

minima:
  skin: classic
#  date_format: "%Y-%m-%d %H:%M"


plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-titles-from-headings

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
