header_title: CPANSec
author: CPAN Security Outreach & Information Project
#email: cpan-security@perl.org
description: >-
  CPAN Security Group (CPANSec)
baseurl: ""
url: "https://security.metacpan.org"
domain: security.metacpan.org
show_excerpts: true

header_pages:
  - docs/report.md
  - docs/pre-release-disclosure.md
  - docs/README.md
  - presentations/README.md

paginate: 4
paginate_path: "/news/all/page:num"

# Build settings
theme: minima

minima:
  skin: classic
  date_format: "%Y-%m-%d %H:%M"


plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-titles-from-headings

social_links:
  - { platform: github,     user_url: "https://github.com/CPAN-Security" }

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
